[package]
name = "listagram"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
cargo-watch = "8.5.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
